"# To install airlines with pathogen
"# git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline

set termencoding=utf-8
set encoding=utf-8
setglobal fileencoding=utf-8
"set fileencodings=ucs-bom,utf-8,latin1

set expandtab ts=4 sw=4 ai 
execute pathogen#infect()
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
"# set statusline+=%*
set wildmenu

hi Search cterm=NONE ctermfg=grey ctermbg=blue
set hlsearch

set list
set listchars=tab:➸>,trail:➠,extends:↚,nbsp:¬

let g:syntastic_python_checkers=['pyflakes','pep8' ]
let g:syntastic_python_pyflakes_args='--ignore=E501,E225,W503'
let g:syntastic_python_pep8_args='--ignore=E501,E225,W503'

let g:syntastic_aggregate_errors = 1
let g:syntastic_always_populate_loc_list = 0
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"# Shut the No Such import issues
let g:syntastic_cpp_gcc_quiet_messages = { 'regex': ['No such'] }

autocmd BufRead,BufNewFile   *.tex set spell spelllang=en_us

let syntastic_mode_map = { 'passive_filetypes': ['asm'] }

colorscheme darkblue
set nocompatible
set bs=2
set ruler
set ts=2
set sw=4
set spell
set spl=en
syntax on
set wrap
set ai

" Omni plugin syntax
"
"$"$filetype plugin on
"$ set omnifunc=syntaxcomplete#Complete

autocmd BufNewfile,BufRead Makefile set noexpandtab
autocmd BufNewfile,BufRead *.c  set expandtab
autocmd BufNewfile,BufRead *.cs  set expandtab
autocmd BufNewfile,BufRead *.cpp set expandtab nospell
autocmd BufNewfile,BufRead *.py  set tabstop=2 shiftwidth=2 expandtab tabstop=4 nospell
autocmd BufNewfile,BufRead *.py set colorcolumn=100

autocmd BufNewfile,BufRead *.js  set expandtab
autocmd BufNewfile,BufRead *.js set tabstop=2
autocmd BufNewfile,BufRead *.js set nospell

autocmd BufNewfile,BufRead *.html  set expandtab
autocmd BufNewfile,BufRead *.html set tabstop=2
autocmd BufNewfile,BufRead *.html set nospell

autocmd BufNewfile,BufRead *.asm  set expandtab
autocmd BufNewfile,BufRead *.asm  set expandtab
autocmd BufNewfile,BufRead *.asm set nospell
autocmd BufNewfile,BufRead *.asm set syn=nasm
autocmd BufNewfile,BufRead *.asm set tabstop=3
set fileformats=unix

set laststatus=2
let g:airline_powerline_fonts = 1 

if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '▶'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.whitespace = 'Ξ'

:hi SpellBad cterm=underline ctermfg=lightyellow ctermbg=red

" Activer la sauvegarde automatique de la position du curseur
if has("autocmd")
  augroup remember_cursor_position
    autocmd!
    autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | execute "normal! g'\"" | endif
  augroup END
endif
