; Define ma structure de structures en mémoire allouée
%define RAMSTRU__SIS_LEN       0x44
%define RAMSTRU__PIS_LEN       0x10
%define RAMSTRU__CTX_LEN       0x2BC + 4
%define RAMSTRU__BBOX_LEN      BBLEN   ; Shuffle Bbox Key 
%define RAMSTRU__FILENAME_LEN  512    ; File + path of runpeexe
%define RAMSTRU__OPTION_LEN    512    ; Option passed to runpe
%define RAMSTRU__PE_LEN        EPELEN   ; PE file

%define RAMSTRU__SIS      0x0
%define RAMSTRU__PIS      RAMSTRU__SIS_LEN 
%define RAMSTRU__CTX      RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN 
%define RAMSTRU__BBOX     RAMSTRU__CTX_LEN + RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN
%define RAMSTRU__FILENAME RAMSTRU__CTX_LEN + RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN + RAMSTRU__BBOX_LEN
%define RAMSTRU__OPTION   RAMSTRU__FILENAME_LEN + RAMSTRU__CTX_LEN + RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN +RAMSTRU__BBOX_LEN
%define RAMSTRU__PE       RAMSTRU__OPTION_LEN +  RAMSTRU__FILENAME_LEN + RAMSTRU__CTX_LEN + RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN +RAMSTRU__BBOX_LEN
%define RAMSTRU__LEN      RAMSTRU__PE_LEN +  RAMSTRU__OPTION_LEN +  RAMSTRU__FILENAME_LEN + RAMSTRU__CTX_LEN + RAMSTRU__SIS_LEN + RAMSTRU__PIS_LEN + RAMSTRU__BBOX_LEN




